a = input('digite qualquer coisa: ')
print('o tipo primitivo desse valor é', type(a))
print('só tem espaço?', a.isspace())
print('é um número? ', a.isnumeric())
print('é alfabético? ', a.isalpha())
print('è alfanumérico?', a.isalnum())
print('è maiúscula? ', a.isupper())
print(' é minúscula? ', a.islower())
print('è capitalizada ', a.istitle())
